<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="AirlineServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/AirlineServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/AirlineServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://services/">
    <import location="AirlineService.wsdl" namespace="http://services/"/>
    <plnk:partnerLinkType name="AirlineInterfaceLinkType">
        <plnk:role name="AirlineInterfaceRole" portType="ns:AirlineInterface"/>
    </plnk:partnerLinkType>
</definitions>
