<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WizardCorrelationProperties.wsdl" targetNamespace="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:ns="http://j2ee.netbeans.org/wsdl/TravelGood/src/client" xmlns:tns="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties">
    <import namespace="http://j2ee.netbeans.org/wsdl/TravelGood/src/client" location="client.wsdl"/>
    <vprop:property name="wzrd_prop_string_string" type="xsd:string"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_string_string" messageType="ns:createItineraryResponse" part="itineraryId"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_string_string" messageType="ns:addHotelOperationRequest" part="itineraryId"/>
</definitions>
