<?xml version="1.0" encoding="UTF-8"?>
<definitions name="getHotels" targetNamespace="http://j2ee.netbeans.org/wsdl/TravelGood/src/getHotels"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/TravelGood/src/getHotels" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="getHotelsOperationRequest">
        <part name="takeoffAirport" type="xsd:string"/>
        <part name="landingAirport" type="xsd:string"/>
        <part name="takeoffDate" type="xsd:date"/>
    </message>
    <message name="getHotelsOperationResponse">
        <part name="part1" type="xsd:anyType"/>
    </message>
    <portType name="getHotelsPortType">
        <operation name="getHotelsOperation">
            <input name="input1" message="tns:getHotelsOperationRequest"/>
            <output name="output1" message="tns:getHotelsOperationResponse"/>
        </operation>
    </portType>
    <binding name="getHotelsBinding" type="tns:getHotelsPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="getHotelsOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/TravelGood/src/getHotels"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/TravelGood/src/getHotels"/>
            </output>
        </operation>
    </binding>
    <service name="getHotelsService">
        <port name="getHotelsPort" binding="tns:getHotelsBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/getHotelsService/getHotelsPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="getHotels">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="getHotelsPortTypeRole" portType="tns:getHotelsPortType"/>
    </plnk:partnerLinkType>
</definitions>
