<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="HotelServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/HotelServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/HotelServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://services/">
    <import location="HotelService.wsdl" namespace="http://services/"/>
    <plnk:partnerLinkType name="HotelInterfaceLinkType">
        <plnk:role name="HotelInterfaceRole" portType="ns:HotelInterface"/>
    </plnk:partnerLinkType>
</definitions>
