<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WizardCorrelationProperties.wsdl" targetNamespace="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:ns="http://services/" xmlns:tns="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties">
    <import namespace="http://services/" location="TravelAgencySoapService.wsdl"/>
    <vprop:property name="wzrd_prop_int_int" type="xsd:int"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_int_int" messageType="ns:createItineraryResponse" part="return"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_int_int" messageType="ns:getHotelsTG" part="id"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_int_int" messageType="ns:getFlightsTG" part="id"/>
</definitions>
