<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="TravelAgencySoapServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/TravelAgencySoapServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/TravelAgencySoapServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://services/">
    <import location="TravelAgencySoapService.wsdl" namespace="http://services/"/>
    <plnk:partnerLinkType name="TravelAgencySoapInterfaceLinkType">
        <plnk:role name="TravelAgencySoapInterfaceRole" portType="ns:TravelAgencySoapInterface"/>
    </plnk:partnerLinkType>
</definitions>
