
package hotel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelInterface", targetNamespace = "http://services/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelInterface {


    /**
     * 
     * @param city
     * @param departureDate
     * @param arrivalDate
     * @return
     *     returns hotel.HotelArray
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "hotels", partName = "hotels")
    @Action(input = "http://services/HotelInterface/getHotelsRequest", output = "http://services/HotelInterface/getHotelsResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://services/HotelInterface/getHotels/Fault/SQLException")
    })
    public HotelArray getHotels(
        @WebParam(name = "city", partName = "city")
        String city,
        @WebParam(name = "arrivalDate", partName = "arrivalDate")
        XMLGregorianCalendar arrivalDate,
        @WebParam(name = "departureDate", partName = "departureDate")
        XMLGregorianCalendar departureDate)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param hotelBookingRequest
     * @return
     *     returns boolean
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services/HotelInterface/bookHotelRequest", output = "http://services/HotelInterface/bookHotelResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://services/HotelInterface/bookHotel/Fault/SQLException")
    })
    public boolean bookHotel(
        @WebParam(name = "hotelBookingRequest", partName = "hotelBookingRequest")
        HotelBookingRequest hotelBookingRequest)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param bookingNumber
     */
    @WebMethod
    @Action(input = "http://services/HotelInterface/cancelHotelRequest", output = "http://services/HotelInterface/cancelHotelResponse")
    public void cancelHotel(
        @WebParam(name = "bookingNumber", partName = "bookingNumber")
        String bookingNumber);

}
